apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ include "helm-poc-chart.name" . }}
  name: {{ include "helm-poc-chart.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: {{ include "helm-poc-chart.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "helm-poc-chart.name" . }}
    spec:
      containers:
      - image: {{ .Values.image.repository }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ .Chart.Name }}
        ports:
        - containerPort: 8080
          protocol: TCP
